<h2>moar stuff!!</h2>
<h3>new id is gonna be <span id="newId"><?php echo $this->newId; ?></span></h3>
<input id="addBr" value="br" type="button">
<input id="addLink" value="link" type="button">
<input id="addStrong" value="strong" type="button">
<input id="addEm" value="em" type="button">
<input id="addVideo" value="video" type="button">
<input id="addProc" value="processing" type="button">
<input id="addImg" value="img" type="button">
<?php echo $this->form ?>