<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>
    </head>

    <div id="container">
        <div class="header">
            <h1><a href="/">&diams;killbodyeatsoul</a></h1>
            <div id="navigation">
                <ul>
                    <li>.<a href="mailto:beast.caged@gmail.com">mail</a></li>
                    <li>.<a href="http://www.killbodyeatsoul.net/eatsoul.rss">rss</a></li>
                    <li>.<a href="http://www.youtube.com/channel/UC-JBL20HHzjNveUzxo83K6Q">youtube</a></li>
                    <li>.<a href="http://vimeo.com/beastcaged">vimeo</a></li>
                    <li>.<a href="http://flickr.com/photos/beastcaged">flickr</a></li>
                    <li>.<a href="http://killbodyeatsoul.tumblr.com/">tumblr</a></li>
                    <li>.<a href="http://soundcloud.com/thickerthanblood-1">soundcloud</a></li>                   
                </ul>
            </div>
        </div>

        <div id="outercontent">
            <div id="innercontent">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>

        <div id="footer">
            <a href="/">&diams;</a>
        </div>
    </div>
    <script type="text/javascript" src="/js/processing.min.js"></script>
    <script type="text/javascript" src="/js/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="/js/main.js"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-36949485-1', 'auto');
        ga('send', 'pageview');
    </script>
</html>
